sonar.projectKey=UPT-FAING-EPIS_proyecto-si783-2026-i-u1-analizador-de-rendimiento-de-consultas
sonar.organization=upt-faing-epis
sonar.host.url=https://sonarcloud.io
sonar.sources=query_analyzer
sonar.tests=tests
sonar.sourceEncoding=UTF-8
sonar.python.version=3.14
sonar.python.coverage.reportPaths=build/reports/coverage.xml
sonar.python.xunit.reportPath=build/test-results/python-quality.xml
sonar.coverage.exclusions=query_analyzer/tui/**,query_analyzer/cli/questionary_prompts.py
