"""Build the academic documentation and quality evidence portal."""

from __future__ import annotations

import html
import re
import shutil
import sys
from pathlib import Path

import markdown

ROOT = Path(__file__).resolve().parents[1]
DOCS_DIR = ROOT / "docs"
SITE_DIR = ROOT / "build" / "pages-site"


def title_for(path: Path) -> str:
    """Resolve a readable HTML title from the first Markdown heading."""
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return path.stem.replace("-", " ")


def render_markdown(source: Path, destination: Path) -> None:
    """Render one Markdown document into the Pages site."""
    raw = source.read_text(encoding="utf-8")
    body = markdown.markdown(
        raw,
        extensions=["extra", "toc", "tables", "fenced_code", "sane_lists"],
        output_format="html5",
    )
    body = re.sub(
        r'href="([^":]+)\.md(#[^"]*)?"',
        lambda match: f'href="{match.group(1)}.html{match.group(2) or ""}"',
        body,
    )
    relative_root = "../" * len(destination.relative_to(SITE_DIR).parents[:-1])
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(
        f"""<!doctype html>
<html lang="es">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{html.escape(title_for(source))}</title>
  <link rel="stylesheet" href="{relative_root}assets/site.css">
</head>
<body><main class="page">{body}</main></body>
</html>
""",
        encoding="utf-8",
    )


def write_status_page(destination: Path, title: str, body: str) -> None:
    """Create a clear placeholder when evidence requires a CI secret or job."""
    destination.mkdir(parents=True, exist_ok=True)
    index = destination / "index.html"
    relative_root = "../" * len(index.relative_to(SITE_DIR).parents[:-1])
    index.write_text(
        f"""<!doctype html>
<html lang="es">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{html.escape(title)}</title>
  <link rel="stylesheet" href="{relative_root}assets/site.css">
</head>
<body><main class="page"><h1>{html.escape(title)}</h1><p>{html.escape(body)}</p></main></body>
</html>
""",
        encoding="utf-8",
    )


def write_reports_index(destination: Path) -> None:
    """Write links to every report generated by the quality workflow."""
    reports = [
        ("coverage", "Cobertura", "Cobertura combinada con umbral verificable."),
        ("unit", "Pruebas unitarias", "Modelos, parsers, configuración y lógica aislada."),
        ("contract", "Contratos de motores", "Contrato común para los 13 motores."),
        ("integration", "Integración", "Motores Docker y servicios emulados."),
        ("bdd", "BDD", "Escenarios Dado/Cuando/Entonces."),
        ("mutation", "Mutación", "Mutantes detectados y sobrevivientes."),
        ("interface", "Interfaz", "Navegación documental con trazas y video."),
        ("security", "Seguridad", "Bandit, Semgrep y auditoría de dependencias."),
        ("sonar", "SonarCloud", "Estado del análisis y Quality Gate."),
        ("vscode", "VS Code", "Pruebas y auditoría de la extensión."),
    ]
    links = "\n".join(
        f'<li><a href="{slug}/">{html.escape(title)}</a>: {html.escape(description)}</li>'
        for slug, title, description in reports
    )
    destination.mkdir(parents=True, exist_ok=True)
    (destination / "index.html").write_text(
        f"""<!doctype html>
<html lang="es">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Reportes de pruebas y calidad</title>
  <link rel="stylesheet" href="../assets/site.css">
</head>
<body><main class="page">
<h1>Reportes de pruebas y calidad</h1>
<p>Evidencias producidas automáticamente para la misma revisión del código.</p>
<ul class="report-grid">{links}</ul>
</main></body>
</html>
""",
        encoding="utf-8",
    )


def main() -> int:
    """Build the complete static site."""
    if SITE_DIR.exists():
        shutil.rmtree(SITE_DIR)
    SITE_DIR.mkdir(parents=True)

    assets = SITE_DIR / "assets"
    assets.mkdir()
    (assets / "site.css").write_text(
        """
:root { color-scheme: light; font-family: Arial, Helvetica, sans-serif; }
body { margin: 0; background: #f5f7fa; color: #20242a; }
.page { max-width: 1080px; margin: 0 auto; padding: 34px 26px 60px; background: white; min-height: 100vh; }
h1, h2, h3 { color: #17202a; line-height: 1.2; }
a { color: #0759b5; }
table { border-collapse: collapse; width: 100%; margin: 16px 0; }
th, td { border: 1px solid #d6d9de; padding: 8px 10px; vertical-align: top; }
th { background: #eef1f5; }
pre { overflow: auto; background: #f0f2f5; padding: 12px; border-radius: 6px; }
code { background: #f0f2f5; padding: 1px 4px; border-radius: 4px; }
img { max-width: 100%; }
.report-grid { display: grid; gap: 10px; padding-left: 20px; }
@media (max-width: 600px) {
  .page { padding: 20px 14px 40px; overflow-wrap: anywhere; }
  table { display: block; overflow-x: auto; }
}
""".strip(),
        encoding="utf-8",
    )
    shutil.copytree(DOCS_DIR / "media", SITE_DIR / "media")

    for source in DOCS_DIR.rglob("*.md"):
        relative = source.relative_to(DOCS_DIR)
        destination = SITE_DIR / relative.with_suffix(".html")
        if relative.name.lower() == "readme.md":
            destination = SITE_DIR / relative.parent / "index.html"
        render_markdown(source, destination)

    reports_root = SITE_DIR / "reports"
    write_reports_index(reports_root)
    for report in (
        "coverage",
        "unit",
        "contract",
        "integration",
        "bdd",
        "mutation",
        "interface",
        "security",
        "sonar",
        "vscode",
    ):
        write_status_page(
            reports_root / report,
            f"Reporte {report}",
            "La evidencia se incorpora al ejecutar el workflow Quality Reports and Pages.",
        )
    return 0


if __name__ == "__main__":
    sys.exit(main())
